import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Navbar";
import { Orbitron } from 'next/font/google'



export const metadata: Metadata = {
  title: `FutureTools.io`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Header/>
        
        {children }
      </body>
    </html>
  );
}
